baseURL = "https://aifactoryhub.org"
languageCode = "en-us"
title = "AIFactoryHub"
theme = "github-style"
[params]
  mainSections = ["posts"]
[taxonomies]
  user = "users"
  tag = "tags"
  category = "categories"
  series = "series"
  archive = "archives"
